In [1]:
import numpy as np

matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix2 = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

# Matrix addition
result = matrix1 + matrix2

print("Result of Matrix Addition:")
print(result)

Result of Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
